first_name = input("Tell me your name, and click enter. ") 
print("\n") 
print("Thanks! Your name is: " + first_name) 
 
input("Press the enter key to continue...") 
print("\n") 
print("Let's begin with your MadLib! It will be based on the song |I knew I loved you| by Savage Garden") 
print("\n") 
mountain = input("Tell me your favourite mountain ") 
mountian_color = input("Whats the color of mountain ") 
River = input("Which River is longest acoording to you ") 
rainbow = input("What is in the sky that shine after Rain ") 
fav_per = input("Who is you fav person ") 
name_fav_per = input("And name of fav person? ") 
noun = input("Tell me any Noun ") 
adjective = input("Tell me any adjective ") 
verb = input("Tell me any Verb ") 
sport = input("Your fav sport? ") 
football = input("What is the shape of football ") 
animal = input("Who is strongest animal according to you ") 
monkey = input("Do you like black monkey or white monkey? ") 
 
print("\n") 
input("Hit enter to generate your MadLib!") 
print("\n") 
print("Maybe it's "+ mountain) 
print("But %s things you just don't question" %mountian_color) 
print("Like in your eyes, I see my %s in an instant" %River) 
print("And there it "+rainbow) 
print("I think I found my "+ fav_per) 
print("\n") 
print("I know %s it might sound"%name_fav_per) 
print("More than a little crazy but I believe "+noun) 
print("\n") 
print("I knew I loved you %s before I met you"%adjective) 
print("\tI think I dreamed you %s into life"%verb) 
print("{} I knew I loved you {} before I met you".format(sport, football)) 
print("\tI have been waiting {} all my life {}".format(animal, monkey)) 
